import AuthProvider from "./provider/AuthProvider";

export const metadata = {
    title: "Protfolio",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body>
                <AuthProvider>{children}</AuthProvider>
            </body>
        </html>
    );
}
